'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class STUDENT
    Public Property ID_STUDENT As Integer
    Public Property NAME As String
    Public Property LAST_NAME As String
    Public Property NATIONALY As String
    Public Property EMAIL As String
    Public Property PASSWORD As String

End Class
